//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webtnonline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ketqua
    {
        public int id { get; set; }
        public Nullable<int> std_id { get; set; }
        public Nullable<int> dethi_id { get; set; }
        public Nullable<int> caudung { get; set; }
        public Nullable<double> diem { get; set; }
    
        public virtual dethi dethi { get; set; }
        public virtual student student { get; set; }
    }
}
