//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webtnonline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public student()
        {
            this.ketquas = new HashSet<ketqua>();
        }
    
        public int std_id { get; set; }
        public string std_name { get; set; }
        public string std_password { get; set; }
        public string std_image { get; set; }
        public string std_MSSV { get; set; }
        public string std_SDT { get; set; }
        public string std_diachi { get; set; }
        public string std_email { get; set; }
        public Nullable<int> id_lop { get; set; }
        public Nullable<int> id_khoa { get; set; }
        public string hoten { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ketqua> ketquas { get; set; }
        public virtual khoa khoa { get; set; }
        public virtual lop lop { get; set; }
    }
}
